import { DocumentTypeName } from "@/types/users";

export const DocumentTypeOptions = [
    { id: 1, label: "Employment Contract", value: DocumentTypeName.EMPLOYMENT_CONTRACT },
    { id: 2, label: "Criminal Record Letter", value: DocumentTypeName.CRIMINAL_RECORD_LETTER },
    { id: 3, label: "Medical Examination", value: DocumentTypeName.MEDICAL_EXAMINATION },
    { id: 4, label: "Psychological Fit Certificate", value: DocumentTypeName.PSYCHOLOGICAL_FIT_CERTIFICATE },
    { id: 5, label: "Trust Exam", value: DocumentTypeName.TRUST_EXAM },
    { id: 6, label: "Toxicological Exam", value: DocumentTypeName.TOXICOLOGICAL_EXAM },
    { id: 7, label: "Common Trunk Certificate", value: DocumentTypeName.COMMON_TRUNK_CERTIFICATE },
    { id: 8, label: "Certificates of Specialities", value: DocumentTypeName.CERTIFICATES_OF_SPECIALITIES },
    { id: 9, label: "EC1099 PipeM Inspectors", value: DocumentTypeName.EC1099_PIPEM_INSPECTORS },
    { id: 10, label: "EC1102 HBS Inspectors", value: DocumentTypeName.EC1102_HBS_INSPECTORS },
    { id: 11, label: "Safety and Hygiene Certificate", value: DocumentTypeName.SAFETY_AND_HYGIENE_CERTIFICATE },
    { id: 12, label: "Training from the Local Airport Security Program", value: DocumentTypeName.TRAINING_FROM_THE_LOCAL_AIRPORT_SECURITY_PROGRAM },
    { id: 13, label: "MRX Operation Record", value: DocumentTypeName.MRX_OPERATION_RECORD },
    { id: 14, label: "DMP Operation Record", value: DocumentTypeName.DMP_OPERATION_RECORD },
    { id: 15, label: "ETD Operation Record", value: DocumentTypeName.ETD_OPERATION_RECORD },
    { id: 16, label: "CTX Operation Record", value: DocumentTypeName.CTX_OPERATION_RECORD },
    { id: 17, label: "CCTV Operation Record", value: DocumentTypeName.CCTV_OPERATION_RECORD },
    { id: 18, label: "Record Security Surveillance Property Real State", value: DocumentTypeName.RECORD_SECURITY_SURVEILLANCE_PROPERTY_REAL_STATE },
    { id: 19, label: "Record in Personal Defense", value: DocumentTypeName.RECORD_IN_PERSONAL_DEFENSE },
    { id: 20, label: "Record Physical Condition", value: DocumentTypeName.RECORD_PHYSICAL_CONDITION },
    { id: 21, label: "Record in Dealing with the Public", value: DocumentTypeName.RECORD_IN_DEALING_WITH_THE_PUBLIC },
    { id: 22, label: "Record First Aid", value: DocumentTypeName.RECORD_FIRST_AID },
    { id: 23, label: "Record Radio Communication", value: DocumentTypeName.RECORD_RADIO_COMMUNICATION },
    { id: 24, label: "Record Preparing Reports", value: DocumentTypeName.RECORD_PREPARING_REPORTS },
    { id: 25, label: "Certificate of Studies", value: DocumentTypeName.CERTIFICATE_OF_STUDIES },
    { id: 26, label: "CURP", value: DocumentTypeName.CURP },
    { id: 27, label: "Birth Certificate", value: DocumentTypeName.BIRTH_CERTIFICATE },
    { id: 28, label: "CUIP", value: DocumentTypeName.CUIP },
    { id: 29, label: "Official Identification", value: DocumentTypeName.OFFICIAL_IDENTIFICATION },
    { id: 30, label: "Proof of Address", value: DocumentTypeName.PROOF_OF_ADDRESS },
    { id: 31, label: "Job Application", value: DocumentTypeName.JOB_APPLICATION },
    { id: 32, label: "IMSS Registration", value: DocumentTypeName.IMSS_REGISTRATION },
  ];
  